auto.waitFor();
var Maid = require("Maid.js");
var maid = new Maid("com.bankcomm.maidanba");
var Unlock = require("Unlock.js");
var unlock = new Unlock();
maid.before();
unlock.unlock();
maid.sleep(2);
maid.killall();
maid.sleep(2);
maid.launch();
maid.sleep(6);
maid.clickIdCenter("center_image");
maid.sleep(2);
maid.clickTextCenter("签到");
maid.sleep(2);
gesture(2000, [291, 871], [549, 871], [291, 1100], [291, 1360], [549, 1100], [549, 1360], [773, 1100]);
maid.sleep(4);
maid.clickTextCenter("签到");
maid.sleep(1);
maid.clickTextCenter("去抽奖");
maid.sleep(2);
maid.clickTextCenter("完成");
maid.sleep(1);
maid.exit();
maid.after();
