auto.waitFor();
var Maid = require("Maid.js");
var maid = new Maid("com.unionpay");
var Unlock = require("Unlock.js");
var unlock = new Unlock();
maid.before();
unlock.unlock();
maid.sleep(2);
maid.killall();
maid.sleep(2);
maid.launch();
maid.sleep(6);
maid.clickIdCenter("frog_float_notgif");
maid.sleep(3);
maid.clickTextCenter("立即签到");
maid.sleep(2);
maid.clickTextCenter("签到完成");
maid.sleep(1);
maid.exit();
maid.after();
