auto.waitFor();
var Maid = require("Maid.js");
var maid = new Maid("com.jingdong.app.mall");
var Unlock = require("Unlock.js");
var unlock = new Unlock();
maid.before();
unlock.unlock();
maid.sleep(2);
maid.killall();
maid.sleep(2);
maid.launch();
maid.sleep(6);
back();
maid.sleep(1);
maid.clickTextCenter("领京豆");
maid.sleep(2);
maid.clickTextCenter("签到领京豆");
maid.sleep(2);
maid.exit();
maid.after();